# This script reads live packet rows generated by tshark,
# preprocesses them to match the training pipeline,
# loads our saved model, and then classifies
# rolling 20-row traffic windows as normal, flood, or slowite_like.

from collections import Counter
from pathlib import Path
import time
import joblib
import pandas as pd

#These are the setting for the script of how big to read, when to alert
#and what files to reference too when running.
BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR.parent/ "Traffic_Data_Sets"

WINDOW_SIZE = 20
POLL_SECONDS = 2
LIVE_FILE = "live_packets.csv"
MODEL_FILE = "rf_model.joblib"
REFERENCE_FILE = "icu_combined_labeled.csv"

#Fill in the missing values so it doesn't crash like in prepared_features.py
def fill_missing(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df["mqtt.topic"] = df["mqtt.topic"].fillna("NONE")
    df["mqtt.msgtype"] = df["mqtt.msgtype"].fillna(-1)
    df["tcp.flags"] = df["tcp.flags"].fillna("0x0000")
    df["tcp.srcport"] = df["tcp.srcport"].fillna(0)
    df["tcp.dstport"] = df["tcp.dstport"].fillna(0)
    df["ip.src"] = df["ip.src"].fillna("0.0.0.0")
    df["ip.dst"] = df["ip.dst"].fillna("0.0.0.0")
    return df

#Converts the texts columns into number codes for easier ML reading like in prepared_features.py
def build_category_maps() -> dict:
    ref = pd.read_csv(REFERENCE_FILE)
    ref = fill_missing(ref)

    maps = {}
    for col in ["ip.src", "ip.dst", "tcp.flags", "mqtt.topic", "label"]:
        categories = ref[col].astype("category").cat.categories
        maps[col] = {value: idx for idx, value in enumerate(categories)}

    return maps

#This turns the tshark rows in ML ready rows
def encode_live(df: pd.DataFrame, category_maps: dict) -> pd.DataFrame:
    df = fill_missing(df)

    #Encode categorical columns
    for col in ["ip.src", "ip.dst", "tcp.flags", "mqtt.topic"]:
        df[col] = df[col].map(category_maps[col]).fillna(-1).astype(int)

    #Force numeric columns
    numeric_cols = ["frame.time_epoch", "tcp.srcport", "tcp.dstport", "frame.len", "mqtt.msgtype"]
    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)

    return df

#This loads our already trained model and reads the live csv by taking
# new rows of 20 and ensuring live data matches the data seen in training and
#during testing and produce a prediction on the type of attack.
def detect_live():
    model_bundle = joblib.load(MODEL_FILE)
    rf = model_bundle["model"]
    feature_columns = model_bundle["feature_columns"]
    label_map = model_bundle["label_map"]

    category_maps = build_category_maps()

    print("Live detector started.")
    print(f"Watching: {LIVE_FILE}")
    print("Press Ctrl+C to stop.\n")

    last_seen_rows = 0

#Reads the live csv
    try:
        while True:
            try:
                live_df = pd.read_csv(LIVE_FILE)
            except FileNotFoundError:
                print("Waiting for live_packets.csv...")
                time.sleep(POLL_SECONDS)
                continue
            except pd.errors.EmptyDataError:
                time.sleep(POLL_SECONDS)
                continue
            except pd.errors.ParserError:
                time.sleep(POLL_SECONDS)
                continue

            if len(live_df) < WINDOW_SIZE:
                time.sleep(POLL_SECONDS)
                continue

            #Only process on new rows
            if len(live_df) == last_seen_rows:
                time.sleep(POLL_SECONDS)
                continue

            #Take newest 20 rows
            window_df = live_df.tail(WINDOW_SIZE).copy()
            window_df = encode_live(window_df, category_maps)

            #Ensures the live data matches the one looked at while training
            X_live = window_df.drop(columns=["frame.time_epoch"], errors="ignore")
            for col in feature_columns:
                if col not in X_live.columns:
                    X_live[col] = 0
            X_live = X_live[feature_columns]

            #Predict row-by-row
            row_preds = rf.predict(X_live)
            row_labels = [label_map[int(p)] for p in row_preds]

            #Majority vote
            counts = Counter(row_labels)
            top_label, top_count = counts.most_common(1)[0]
            confidence = top_count / len(row_labels)

            #Keeps the original raw window and finds the row that matches the prediction
            raw_window = live_df.tail(WINDOW_SIZE).copy()
            atk_rows = raw_window[[label == top_label for label in row_labels]]
            atk_rows = atk_rows[atk_rows["tcp.dstport"] == 1883]
            sus_ip = None
            if not atk_rows.empty and top_label in {"flood", "slowite_like"}:
                sus_ip = atk_rows["ip.src"].value_counts().idxmax()

            #Decides on to alert or not
            print("===================================")
            print(f"I think is a {top_label} ")
            print(f"I am {confidence:.2f} confident")
            if sus_ip:
                print(f"This IP looks sus {sus_ip}")
            print("===================================\n")

            last_seen_rows = len(live_df)
            time.sleep(POLL_SECONDS)

    except KeyboardInterrupt:
        print("\nStopped live detector.")


if __name__ == "__main__":
    detect_live()